AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/*'
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 100
